export const hover_zh = {
  //description
  setDescription: "test",
  //configuration
  setConfiguration: "測試",
  allowedLanguages: "測試",
  maxZipSize: "測試",
  tags: "測試",
  quota: "test",
  aiTA: "test",
  aiModel: "test",
  selectAPIKeys: "test",
  activeAiKeys: "test",
  inactiveAiKeys: "test",
  trialMode: "test",
  trialMaxNumber: "test",
  resultVisible: "test",
  resultDownloadable: "test",
  uploadPublicTestData: "test",
  uploadACFiles: "test",
  networkSidecars: "test",
  networkAccessRestriction: "test",
  networkAccessModel: "test",
  networkAccessIPList: "test",
  networkAccessURLList: "test",
  SandboxEnvironment: "test",
  Sidecars: "test",
  dockerFiles: "test",
  ArtifactCollection: "test",
  CompiledBinary: "test",
  StudentArtifact: "test",
  sideCarName: "test",
  sideCarImage: "test",
  sideCarArgs: "test",
  sideCarEnv: "test",
  //pipeline
  setPipelines: "test",
  fileAccess: "test",
  libraryRestrictionsGroup1: "test",
  libraryRestrictionsGroup2: "test",
  importsRestrictions: "test",
  headersRestrictions: "test",
  functionsRestrictions: "test",
  syntaxRestrictions: "test",
  executionMode: "test",
  executionModeGeneral: "test",
  executionModeFuncitonOnly: "test",
  executionModeInteractive: "test",
  uploadFile: "test",
  interactiveTeacherFirsts: "test",
  interactiveUploadTeacherCode: "test",
  customChecker: "test",
  uploadCustomChecker: "test",
  uploadCustomScorer: "test",
  customScoringScript: "test",
  aiCheckerEnable: "test",
  //set test data
  setTestData: "test",
  setDataZipFile: "test",
  //resource data
  setResourceData: "test",
  setResourceDataStudent: "test",
  setResourceDataTeacher: "test",
  //member
  student:"學生",
  TA:"助教"
};
