export const hover_en = {
  // Description
  setDescription: "Set the problem description, including title, content, example test cases, etc.",

  // Configuration
  setConfiguration: "Configure basic settings like problem name, quota, allowed languages, etc.",
  allowedLanguages: "Select the programming languages allowed for students.",
  maxZipSize: "Set the maximum size limit (MB) for student ZIP uploads.",
  tags: "Set tags for the problem to facilitate categorization and search (comma separated).",
  quota: "Set the submission limit per student count, -1 means unlimited.",

  // AI Teaching Assistant
  aiTA: "Enable AI Teaching Assistant, allowing students to get hints via AI.",
  aiModel: "Select the model version used by the AI assistant.",
  selectAPIKeys: "Select API keys available for this problem (multiple selection allowed).",
  activeAiKeys: "Currently active API keys, will be used in rotation.",
  inactiveAiKeys: "Inactive API keys (drag to active list to enable).",

  // Trial Mode
  trialMode: "Enable Trial Mode, allowing students to test run their code before formal submission.",
  trialMaxNumber: "Set the execution limit for Trial Mode, -1 means unlimited.",
  resultVisible: "Allow students to view detailed results and error messages of trial runs.",
  resultDownloadable:
    "Allow students to download output files from trial runs (only valid if result is visible).",
  uploadPublicTestData: "Upload public test data ZIP for Trial Mode (containing .in and .out files).",
  uploadACFiles: "Upload Correct Answer (AC/Reference) code.",

  // Network & Sidecars
  networkSidecars: "Configure Sidecar containers to provide extra network services.",
  networkAccessRestriction: "Set external network access restrictions.",
  networkAccessModel: "Blacklist (Default allow undefined) or Whitelist (Default block undefined).",
  networkAccessIPList: "Set the list of allowed or blocked IP addresses.",
  networkAccessURLList: "Set the list of allowed or blocked URLs.",

  // Sandbox Environment
  SandboxEnvironment: "Configure the sandbox environment and Docker image for execution.",
  Sidecars: "Configure auxiliary containers (Sidecars) running alongside the main program.",
  dockerFiles: "Upload custom Dockerfile to build the execution environment.",

  // Sidecar Details
  sideCarName: "Sidecar container name.",
  sideCarImage: "Docker image name used by the Sidecar.",
  sideCarArgs: "Startup arguments passed to the Sidecar container.",
  sideCarEnv: "Environment variables for the Sidecar container.",

  // Artifacts
  ArtifactCollection: "Set files to be collected from the execution environment (Artifacts).",
  CompiledBinary: "Collect the compiled binary executable.",
  StudentArtifact: "Collect specific files generated by student code.",

  // Pipeline
  setPipelines: "Configure the code compilation and execution pipeline.",
  fileAccess: "Set file system access permissions for student code.",
  libraryRestrictionsGroup1: "Set static analysis and library usage restrictions.",
  libraryRestrictionsGroup2: "Set advanced library and syntax restrictions.",
  importsRestrictions: "Restrict modules (Imports) that Python scripts can import.",
  headersRestrictions: "Restrict headers (Headers) that C/C++ programs can include.",
  functionsRestrictions: "Restrict specific functions the program can call.",
  syntaxRestrictions: "Restrict syntax structures the program can use (e.g., for, while, etc.).",
  executionMode: "Select program execution mode (General, Interactive, etc.).",
  executionModeGeneral: "General Mode: Standard I/O (stdin/stdout) judgment.",
  executionModeFunctionOnly: "Function Only Mode: Students implement specific functions (LeetCode style).",
  executionModeInteractive: "Interactive Mode: Student program needs to interact with a judge program.",
  uploadFile: "Upload related files (e.g., Makefile, Header, etc.).",
  interactiveTeacherFirsts: "Interactive Mode Setting: Whether to execute teacher's code first.",
  interactiveUploadTeacherCode: "Upload teacher's code (Interactor) for Interactive Mode.",
  customChecker: "Enable Custom Checker (Special Judge).",
  uploadCustomChecker: "Upload custom checker script (Python).",
  uploadCustomScorer: "Upload custom scorer script.",
  customScoringScript: "Enable custom scoring logic.",
  aiCheckerEnable: "Enable AI-based checking (AI Checker).",

  // Test Data
  setTestData: "Manage Test Data.",
  setDataZipFile: "Upload ZIP file containing all test data.",

  // Resource Data
  setResourceData: "Set Resource Files.",
  setResourceDataStudent: "Upload resource files accessible to students.",
  setResourceDataTeacher: "Upload resource files for judging use only.",

  // Member
  student: "Student",
  TA: "TA",
};
